### PR TITLE
Create a button to start fine-tuning

### PR DESCRIPTION
**Pull request by katsudoon1**

### CODE REVIEW

**Review by k-taro56 — CHANGES_REQUESTED** [review]
Please implement only one feature per pull request.

**Comment by katsudoon1** [comment]
What is problem ?

**Review by k-taro56 — APPROVED** [review]
I have already solved the above problem.
But I think the button should be disabled or hidden when not needed.

**Comment by k-taro56** [comment]
I am going to close this pull request and make a new issue. I want you to do that.

**Comment by k-taro56** [comment]
I made the issue #68.

**Comment by katsudoon1** [comment]
Thanks. It's my responsibility.

**Review by umiyuri777 — APPROVED** [review]

**Pull request merged**
