### PR TITLE
[editor] Download and Display the specified File ID

### PR DESCRIPTION
**Pull request by k-taro56**

### CODE REVIEW

**Comment by k-taro56** [comment]
[This issue might be related.](https://github.com/vercel/next.js/issues/56253)

**Comment by k-taro56** [comment]
I was able to build after downgrading to 13.4.19.

**Comment by yohrdy243** [comment]
Hi, I have encountered the same problem. I am using Next.js 14.0.1, and the issue remains unresolved. However, the solution is to downgrade to Next.js version 13.4.19. You can achieve this by running the following command: `npm i next@13.4.19`. This should resolve the problem for you.

**Comment by k-taro56** [comment]
Hi. Thanks for your comment.
What projects are you using Next.js for?
For this project, downgrading Next.js to 13.4.19 will only make the build succeed, but this feature will not work. This is because dynamic routing was not (and still is not) supported when doing static site generation (`next export`) with AppRouter.
Next.js 13.4.20 simply adds a build error that dynamic routing is not supported when generating static sites.
So we decided to modify the feature itself to avoid using dynamic routing.
We look forward to hearing from you and will help in any way we can.

**Pull request merged**
